/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class Beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Beranda.class.getName());

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSambutan = new javax.swing.JLabel();
        lblSubSambutan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCekBerat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCekAir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCekKalori = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSambutan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblSambutan.setText("Halo, Fitters !");
        getContentPane().add(lblSambutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 30));

        lblSubSambutan.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        lblSubSambutan.setText("Yuk, cek kesehatan kamu");
        getContentPane().add(lblSubSambutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cek Berat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ideal Kamu!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnCekBerat.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        btnCekBerat.setText("Mulai");
        btnCekBerat.addActionListener(this::btnCekBeratActionPerformed);
        getContentPane().add(btnCekBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Berapa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 274, -1, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kebutuhan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 294, -1, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Air Kamu?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 314, -1, 30));

        btnCekAir.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        btnCekAir.setText("Mulai");
        btnCekAir.addActionListener(this::btnCekAirActionPerformed);
        getContentPane().add(btnCekAir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cari Tahu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        btnCekKalori.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        btnCekKalori.setText("Mulai");
        btnCekKalori.addActionListener(this::btnCekKaloriActionPerformed);
        getContentPane().add(btnCekKalori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 120, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kalori Yang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 30));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dibutuhkan!");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 474, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambar2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 620));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekKaloriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekKaloriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekKaloriActionPerformed

    private void btnCekBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekBeratActionPerformed

    private void btnCekAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekAirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Beranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekAir;
    private javax.swing.JButton btnCekBerat;
    private javax.swing.JButton btnCekKalori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSambutan;
    private javax.swing.JLabel lblSubSambutan;
    // End of variables declaration//GEN-END:variables
}
