/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(360, 640);
        setResizable(false);
        setLocationRelativeTo(null);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambar1.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblKataSandi = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        chkTampilkan = new javax.swing.JCheckBox();
        txtKataSandi = new javax.swing.JPasswordField();
        lblBackground = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(0, 51, 255));
        lblJudul.setText("FitPlus");
        getContentPane().add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, 50));

        lblEmail.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 20));

        txtEmail.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, 30));

        lblKataSandi.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lblKataSandi.setForeground(new java.awt.Color(255, 255, 255));
        lblKataSandi.setText("Kata Sandi");
        getContentPane().add(lblKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));

        btnLogin.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 300, 30));

        chkTampilkan.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        chkTampilkan.setForeground(new java.awt.Color(255, 255, 255));
        chkTampilkan.setText("Tampilkan Kata Sandi");
        chkTampilkan.addActionListener(this::chkTampilkanActionPerformed);
        getContentPane().add(chkTampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 20));

        txtKataSandi.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        txtKataSandi.addActionListener(this::txtKataSandiActionPerformed);
        getContentPane().add(txtKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 300, 30));

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambar1.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // Ambil teks dari kolom input
    String email = txtEmail.getText().trim();
    String sandi = new String(txtKataSandi.getPassword());

    // Validasi: tidak boleh kosong
    if (email.isEmpty() || sandi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email dan Kata Sandi tidak boleh kosong!");
        return;
    }

    try {
        // Buka koneksi ke database
        Connection conn = KoneksiDB.bukaKoneksi();
        
        // Perintah SQL untuk cek data
        String sql = "SELECT * FROM pengguna WHERE email = ? AND kata_sandi = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, email);
        pst.setString(2, sandi);
        
        ResultSet rs = pst.executeQuery();

        // Cek apakah data cocok
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Login Berhasil!");
            
            // Buka halaman Beranda, tutup halaman Login
            new Beranda().setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Email atau Kata Sandi SALAH!");
        }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtKataSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKataSandiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKataSandiActionPerformed

    private void chkTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTampilkanActionPerformed
        // TODO add your handling code here: // Kalau dicentang → tampilkan teks asli
        if (chkTampilkan.isSelected()) {
            txtKataSandi.setEchoChar((char) 0); // 0 = tidak ada karakter penyamaran
        } else {
            // Kalau tidak dicentang → kembali jadi titik-titik
            txtKataSandi.setEchoChar('•'); // bisa ganti '*' juga
        }
    }//GEN-LAST:event_chkTampilkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkTampilkan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKataSandi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKataSandi;
    // End of variables declaration//GEN-END:variables
}
